# build
markdown: kramdown # kramdown, rdiscount
permalink: pretty # /blog/:year/:title/
# Files and folders with underscores prepending the name will not be copied to the final, generated website.
gems:
  - jekyll-redirect-from
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - STYLE_REFERENCE.txt
  - README.md
  - vendor/
  - vnu/
  - vnu.zip 
layouts: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# Main addresses (don't include slash at end)
url: "http://bobspunt.com"
baseurl: ""
# theme
noita:
  name: Bob Spunt
  description: Postdoctoral Fellow
  author:
    name: Bob Spunt
    url: http://bobspunt.com/
  lang: en
  favicons:
    - /public/img/icon_200x200.png
  topbar:
    toggle: Menu
    right:
      - title: "About"
        url: "/about/"
      - title: "CV"
        url: "/cv/"
      - title: "Papers"
        url: "/papers/"
      - title: "Code"
        url: "/code/"
        dropdown:
        - title: "bspmview | SPM Image Viewer"
          url: "http://spunt.github.io/bspmview"
        - title: "Why/How Localizer Task"
          url: "http://spunt.github.io/whyhowlocalizer"
        - title: "fMRI Design Optimization Software"
          url: "http://spunt.github.io/easy-optimize-x"
        - title: "Psychtoolbox Utilities"
          url: "http://spunt.github.io/ptb-utilities"
        - title: "GitHub Repositories"
          url: "https://github.com/spunt?tab=repositories"
      - title: "Resources"
        url: "/resources/"
        dropdown:
        - title: "Links"
          url: "/resources/links/"
        - title: "Teaching"
          url: "/resources/teaching/"
        - title: "Reference"
        - url: "/resources/reference/"
      # - title: "Blog"
      #   url: "/blog/"
      #   class: small button
