# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:
  - jekyll
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from

# Permalinks
permalink:        pretty
# relative_permalinks: true
url:              "http://bobspunt.com"
baseurl:          "/"

# Setup
title:            'Bob Spunt, PhD'
tagline:          'Bob Spunt has a PhD'
description:      'Bob Spunt, PhD'
author:
  name: Bob Spunt
  url: http://bobspunt.com
lang: en
favicons:
  - "public/img/icon_200x200.png"

# Custom vars
google_analytics_tracking_id: UA-56476723-1
paginate:         5

# version:          2.1.0
# github:
  # repo:           https://github.com/poole/hyde
